name: Docker Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Use docker/metadata-action
      id: meta
      uses: docker/metadata-action@v3

    - name: Extract version
      id: version
      run: echo ::set-output name=VERSION::${{ steps.meta.outputs.version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          latest
          major
          major.minor
          v${{ steps.version.outputs.VERSION }}
