name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Use Docker Meta Action
      uses: docker/metadata-action@v3
      with:
        images: ggreen96777/ci-project-green
        tags: latest, major, major.minor
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ggreen96777/ci-project-green .

    - name: Push Docker image to DockerHub
      run: |
        docker push ggreen96777/ci-project-green:latest
        if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref_type }}" == 'tag' ]]; then
          docker push ggreen96777/ci-project-green:${{ github.ref }};
        fi
